### ISSUE TITLE
mp4analyser does not process mp4 files > approx. 2,5 GB

### ISSUE THREAD

**Issue by Pleonasmus** [essential61/mp4analyser#20]
Just today I started to use mp4analyser. It is a very helpul tool, thanks to the author. However, it only managed to load a mp4 file of 2.713.599.692 Bytes length (and any smaller file I used), but failed with another mp4 file with 3.249.745.066 Bytes in length and larger ones.

It throws exceptions:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Doc\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4analyser.py", line 174, in open_file
    new_file = mp4.iso.Mp4File(filename)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 57, in __init__
    current_box = box_factory(f, current_header, self)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 41, in box_factory
    the_box = _box_class(fp, header, parent)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 258, in __init__
    current_box = box_factory(fp, current_header, self)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 41, in box_factory
    the_box = _box_class(fp, header, parent)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 258, in __init__
    current_box = box_factory(fp, current_header, self)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 41, in box_factory
    the_box = _box_class(fp, header, parent)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 258, in __init__
    current_box = box_factory(fp, current_header, self)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 41, in box_factory
    the_box = _box_class(fp, header, parent)
  File "D:\Entwicklungsprojekte\MP4 Analyzer\mp4\iso.py", line 548, in __init__
    bytes_left = self.size - (self.header.length + 8)
AttributeError: 'Header' object has no attribute 'length'

I'm just running the module from the idle shell.

Installed Python version:
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32

I'm running WINDOWS 10 Home, Version 10.0.18362 Build 18362 on my PC.

Best regards

**Comment by essential61** [comment]
Hi,
Can you try changing line 548 of iso.py from
            
    bytes_left = self.size - (self.header.length + 8)

to 

   bytes_left = self.size - (self.header.header_size + 8)

Let me know if it works.

Steven

**Comment by Pleonasmus** [comment]
Dear Steven,

 

thanks for your quick response! Your proposed code change works! I’ve a collection of 15 mp4 files ranging from 2.714 kB to 8.711.354 kB in size from various sources (Smartphone, Video Editing Software and Frame Grabber). They now all can be loaded and analyzed without any problems, thanks again!

 

May I rise a question related to the mp4 files:

I’m currently working with a new surveillance camera generating mp4 files. These files cause trouble when processing them on my PC: Creating previews in the explorer or executing drag & drop often leads to a hard disk load of 100% for typically 2,5 minutes for about 25 files of a few 100 MB each.

I never observed such an effect with any other mp4 files (see above). Trying to import in (usually very stable) video editing software leads to a complete crash without any message. The Windows “Movie & TV” app cannot play some of the mp4 files with error code “„0xc00d36c4“. When inspecting these files with your analyzer, there are some specific findings in contrast to “normal” mp4 files:

*	They contain more than 30.000 mdat atoms for the video stream instead of one or a few
*	Your analyzer says for all mdat atoms: "message": "No samples found."

As compared to your experience: Is this usual? Is this compliant with the standard? I downloaded the standard but I was not yet able to get into all the details.

 

Could you please comment on this?

 

Thanks and kind regards

Hans-Joachim

 

Von: essential61 <notifications@github.com> 
Gesendet: Samstag, 6. Juni 2020 08:48
An: essential61/mp4analyser <mp4analyser@noreply.github.com>
Cc: Pleonasmus <hjrabenb@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [essential61/mp4analyser] mp4analyser does not process mp4 files > approx. 2,5 GB (#20)

 

Hi,
Can you try changing line 548 of iso.py from

bytes_left = self.size - (self.header.length + 8)

to

bytes_left = self.size - (self.header.header_size + 8)

Let me know if it works.

Steven

**Comment by essential61** [comment]
Hi Hans,
The issue was not with file size. Some atoms/boxes such as 'tsel' are quite rare, so the code may not have been exercised before.

Regarding your query I can make some general comments. 

Files conforming to the MP4 standard generally have 1 of 2 formats. 

Firstly, there is the monolithic mp4 file format where there is a single 'moov' box containing metadata and a single 'mdat' box containing the media samples. Within the 'moov' box are series of tables underneath the stbl atom that effectively provide an index to the individual frames of the video within the mdat.

The second format is "fragmented mp4", used in applications like mpeg-dash where there is a 'moov' atom at the beginning that does NOT contain sample tables but just generic metadata, followed by an alternating sequence of 'moof' and 'mdats' where the moof contains the pointers to the individual samples of the following mdat.

I suspect your camera files are some kind of hybrid between the above 2 formats and you need to find out where the sample tables are located. There may be some private uuid atoms defined.

Steven

**Comment by Pleonasmus** [comment]
Hi Steven,

 

thanks again for your quick response. Yes, your are right: Just by accident my biggest mp4 files are the only containing the “tsel” box. Everything fine now.

 

I inspected the “strange” mp4 files a bit more in detail: Apparently they consist of one “mdat” atom per video frame, meaning that a ~20-minute video at 25fps has more than 30.000 subsequent “mdat”s in the file. But there is only one “moov” structure at the end of the file (no “moof” or alternating “moof”-“mdat” sequence). The “stco” atom contains a list of more than 30.000 pointers to the individual “mdat”s. This might cause software components to “endlessly” seek through the files. Apparently, some video editors and Movie & TV are even not able to handle such a structure.  Your analyzer helped a lot.

 

Hans-Joachim

 

 

Von: essential61 <notifications@github.com> 
Gesendet: Samstag, 6. Juni 2020 12:21
An: essential61/mp4analyser <mp4analyser@noreply.github.com>
Cc: Pleonasmus <hjrabenb@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [essential61/mp4analyser] mp4analyser does not process mp4 files > approx. 2,5 GB (#20)

 

Hi Hans,
The issue was not with file size. Some atoms/boxes such as 'tsel' are quite rare, so the code may not have been exercised before.

Regarding your query I can make some general comments.

Files conforming to the MP4 standard generally have 1 of 2 formats.

Firstly, there is the monolithic mp4 file format where there is a single 'moov' box containing metadata and a single 'mdat' box containing the media samples. Within the 'moov' box are series of tables underneath the stbl atom that effectively provide an index to the individual frames of the video within the mdat.

The second format is "fragmented mp4", used in applications like mpeg-dash where there is a 'moov' atom at the beginning that does NOT contain sample tables but just generic metadata, followed by an alternating sequence of 'moof' and 'mdats' where the moof contains the pointers to the individual samples of the following mdat.

I suspect your camera files are some kind of hybrid between the above 2 formats and you need to find out where the sample tables are located. There may be some private uuid atoms defined.

Steven
