### ISSUE TITLE
mdat atoms not parsed when several mdat in the stream

### ISSUE THREAD

**Issue by jcdr428** [essential61/mp4analyser#23]
Hi @essential61 , an interesting mp4 with several mdat atoms:
https://1drv.ms/v/s!AuYcZ0yHv3Dt5jQbgvK55jzqb9Fs?e=TuHvxl

None of the mdat boxes are parsed (message": "No samples found.")

**Comment by essential61** [comment]
I'll have to add some additional logic to  _generate_samples_from_moov() in order to cover corner case of the entries in sample tables spanning multiple mdats

**Comment by jcdr428** [comment]
Good work, thank you Steven !

**Comment by essential61** [comment]
Looks like this now works with no regressions so I'll close the issue.
