### ISSUE TITLE
Enhancement on HexView

### ISSUE THREAD

**Issue by LiMinggang** [essential61/mp4analyser#5]
@essential61 thanks for your work on such a nice tool.

Is it possible to do a enhancement on the hexview to highlight the selected bytes on the ascii data? And print a title and side column for offset of bytes

Like below:
![MadEdit-Mod -  D__DEV_software_mp4analyser-master_mp4analyser py](https://user-images.githubusercontent.com/4847132/70785744-174eed00-1dc6-11ea-8c8e-88779abee05d.png)

**Comment by essential61** [comment]
Hi Minggang,
I'm flattered that you like the tool. FYI, I have recently started a new job so that is likely to take priority over the next month or so.
As regards your feature request, I am more than happy for someone (including yourself) to fork my repo and to add features as they see fit. Actually, the feature you describe is available with most general-purpose hex viewing tools and a very practical usage scenario would be to use my tool to view the structure of the mp4 alongside a general-purpose hex tool (indeed this is what I have been doing using KDE Okteta).

**Comment by LiMinggang** [comment]
Thanks for your response. I've done some changes in the forked one. I'm not sure if you would be interested.
1. Highlight the length error in Header with RED
2. Catch the decode error/exception and stop decoding, then display the correct parts for malformed files.
3. Refactor the factory pattern with globals like below:
```
def box_factory(fp, header, parent):
    """
    box_factory() takes a box type as a parameter and, if a class has been defined for that type, returns
    an instance of that class.
    """
    the_box = None
    box_type = header.type
    _box_class = globals().get(box_type.capitalize()+'Box') # globals() Return a dictionary representing the current global symbol table
    if _box_class:
        the_box = _box_class(fp, header, parent)
        return the_box
    else:
        return mp4.non_iso.box_factory_non_iso(fp, header, parent)
```

**Comment by LiMinggang** [comment]
![2019-12-16 15_53_17-Window](https://user-images.githubusercontent.com/4847132/70888916-58403f00-201c-11ea-80b4-566e7cb2494f.png)

**Comment by essential61** [comment]
Hi Minggang, I'll take a closer look at your proposals over the next few days, but I particularly like your trick in 3 ;-)  (although it probably warrants a comment in the source code to make sense to the casual programmer).
BTW your initial communication did prompt me to fix a couple of non-related, sloppy operator precedence bugs for bitwise operations.

**Comment by LiMinggang** [comment]
Hi, @essential61, I noticed your change and am going to merge them to mine. Thanks for your work!

**Comment by essential61** [comment]
@LiMinggang , would you be able to make a pull request on my repo for the box_factory change?
BTW I think we need a .replace(' ', '_') just before the object creation specifically for the 'url ' and 'urn ' box types

**Comment by LiMinggang** [comment]
Sure, @essential61, I will do a pull request.

**Comment by essential61** [comment]
謝謝 @LiMinggang 
I'll close this issue now if you have no objection. Feel free to continue to make suggestions. I'll be watching your repo anyway. I'll also be updating my wiki page in the next few days.

**Comment by LiMinggang** [comment]
No problem. Please keep improving the tool.
